### ISSUE TITLE
Website > Contact us > Improve dropdown in Contact page

### ISSUE THREAD

**Issue by kdutia** [climatepolicyradar/website#21]
- [ ] refine the list of topic options - @michal-nachmany to provide list of options
- [ ] change options in reason for contact us drop down based on list provided by @michal-nachmany 
- [x] style dropdown to match the rest of the site

**Comment by eurolife** [comment]
There doesn't appear to be a way to style the drop down options as their appearance is dependent on the user's OS.

I don't think we decided on how to change the wording of them, so this still needs to be discussed.
