### ISSUE TITLE
Early Access requestor should be asked additional signup questions

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/website#70]
When completing the Early Access Request form, the user should be asked additional questions.
The form should be displayed in a separate page rather than a popup modal window.

Link to current google form to replicate: https://docs.google.com/forms/d/1AvKRStCgjWgKnh5dDQW-s-XspXQKqD2JhMOz75MqCbU/edit

Also add these fields/options:

- Affiliation type - display the following values:
  - Academia
  - Public sector
  - Private sector
  - IGO
  - NGO/not-for-profit organisation
  - Individual
  - Other
The user should enter the same email address in the "Email" and "Re-enter email" fields. If there is a difference between the two, an error should be displayed.

If "Other" is selected, the user should be able to enter a free text affiliation type. This field will be disabled unless "Other" is selected.

**Comment by eurolife** [comment]
Request early access form has been amended to include all the fields used in the Google form that is currently being used as the 2nd step in the user interview process. This form is responsive, working on all screen sizes.

**Form validation**

- If the user doesn't select any of the checkboxes for questions that have them as options, an error message displays.
- If the user selects the 'Other' option, the 'Other' text input box becomes visible.
- If the user selects the 'Other' option and the corresponding 'Other' text box is not filled in, an error message displays.
- Other fields utilise the built in HTML5 validation available for required or special field types such as email fields.
- When the form is successfully filled out, the message will be sent and a 'Thank You' message is displayed.

How the form submission looks:

![Screenshot 2022-02-10 at 15.36.50.png](https://images.zenhubusercontent.com/613f26adef60f1ed32f09162/2e317ae4-4f2a-46a7-923f-2d0fe8e72bf4)

**Comment by eurolife** [comment]
Final minor changes done, this is now live on the website.
